adidaphat.net.vn/trunk/WeddingInvitation/Areas/Administrator/Controllers/StaticPageController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Telerik.Web.Mvc;
using WeddingInvitation.Areas.Administrator.Models;
using WeddingInvitation.Core.Models.ContentManagement;
using WeddingInvitation.Infrastructure.Mvc;
using WeddingInvitation.Infrastructure.Security;
using WeddingInvitation.Services.ContentManagement;
using WeddingInvitation.Services.Infrastructure;

namespace WeddingInvitation.Areas.Administrator.Controllers
{
    [SuperAdminAuthorize]
    public class StaticPageController : ControllerBase<IStaticPageRepository, StaticPage>
    {
        public StaticPageController(IUnitOfWork unitOfWork, IStaticPageRepository repository)
            : base(repository, unitOfWork)
        {
        }

        //
        // GET: /Administrator/StaticPage/

        public ActionResult Index()
        {
            return View();
        }

        [GridAction]
        public ActionResult GridModel(string search)
        {
            var user = Repository.Search(search);

            var gridModel = new GridModel<StaticPageModel>
            {
                Data = user.Select(x => new StaticPageModel
                                            {
                                                StaticPageId = x.StaticPageId,
                                                Description = x.Description
                                            })
            };
            return new JsonResult
            {
                Data = gridModel
            };
        }

        public virtual ActionResult Edit(int id)
        {
            var entity = Repository.GetById(id);
            var model = new StaticPageModel()
            {
                Content = HttpUtility.HtmlDecode(entity.Content),
                Description = entity.Description,
                StaticPageId = entity.StaticPageId

            };
            return View("Edit", model);
        }

        [HttpPost, ValidateInput(false)]
        public virtual ActionResult Save(StaticPageModel staticPageModel)
        {
            if (staticPageModel.StaticPageId > 0)
            {
                if (!ModelState.IsValid)
                {
                    var entity = Repository.GetById(staticPageModel.StaticPageId);
                    var model = new StaticPageModel()
                    {
                        Content = HttpUtility.HtmlDecode(entity.Content),
                        Description = entity.Description,
                        StaticPageId = entity.StaticPageId

                    };
                    return View("Edit", model);
                }

                var staticPageEntity = Repository.GetById(staticPageModel.StaticPageId);
                staticPageEntity.Content = staticPageModel.Content;
                staticPageEntity.Description = staticPageModel.Description;
                using (UnitOfWork)
                {
                    Repository.Update(staticPageEntity);
                }
            }

            //Save success
            this.SetSuccessNotification(string.Format("{0} đã được lưu thành công.", "Bài viết"));
            return RedirectToAction("Index", new { area = "Administrator" });
        }
    }
}

adidaphat.net.vn/trunk/WeddingInvitation/Areas/Administrator/Views/StaticPage/Edit.cshtml
@model WeddingInvitation.Areas.Administrator.Models.StaticPageModel
<script src="@Url.Content("~/Scripts/Views/Shared/tiny_mce/tiny_mce.js")" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(
    function () {
        tinyMCE.init({
            // General options
            mode: "textareas",
            theme: "advanced",
            plugins: "autolink,lists,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",

            // Theme options
            theme_advanced_buttons1: "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
            theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
            theme_advanced_buttons3: "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
            theme_advanced_buttons4: "insertlayer,moveforward,movebackward,absolute,|,styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,blockquote,pagebreak,|,insertfile,insertimage",
            theme_advanced_toolbar_location: "top",
            theme_advanced_toolbar_align: "left",
            theme_advanced_statusbar_location: "bottom",
            theme_advanced_resizing: true,

            // Skin options
            skin: "o2k7",
            skin_variant: "silver",

            // Drop lists for link/image/media/template dialogs
            template_external_list_url: "js/template_list.js",
            external_link_list_url: "js/link_list.js",
            external_image_list_url: "js/image_list.js",
            media_external_list_url: "js/media_list.js",

            // Replace values for the template plugin
            template_replace_values: {
                username: "Some User",
                staffid: "991234"
            }
        });
    }
);
</script>
@{
    ViewBag.Title = "Sửa bài viết";
}
  
@using (Html.BeginForm("Save", "StaticPage", FormMethod.Post))
{
    <div class="section-header">
        <div class="title">
            <img src="@Url.Content("~/Areas/Administrator/Content/images/ico-catalog.png")" alt="" />
            Sửa bài viết
        </div>
        <div class="options">
            <button type="submit" name="save" value="save" class="t-button">Lưu</button>
            <a href="@Url.Action("index")" class="t-button">Quay lại</a>
        </div>
    </div>
    
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.StaticPageId)
    <table width="100%">
        <tr>
            <td class="adminTitle">
                @Html.Label("Mô tả")
            </td>
            <td class="adminData">
                @Html.TextBoxFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </td>
        </tr>
        <tr>
            <td valign="top" class="adminTitle">
                @Html.Label("Nội dung")
            </td>
            <td>
                @Html.TextAreaFor(model => model.Content, new { style = "height:500px; width:100%;" })
            </td>
        </tr>
    </table>
    <br />
}

adidaphat.net.vn/trunk/WeddingInvitation/Areas/Administrator/Views/StaticPage/Index.cshtml
@{
    ViewBag.Title = "Danh sách các trang tĩnh";
}
<script type="text/javascript">
    $(document).ready(function () {
        new SearchHelper($("#txtSearch"), $("#btnSearch"), $("#StaticPage"));
    });
</script>
<div class="section-header">
    <div class="title">
        <img src="@Url.Content("~/Areas/Administrator/Content/Images/ico-catalog.png")" alt="" />
        Danh sách các trang tĩnh
    </div>
    <div class="options">
    </div>
</div>
<div style="display: none;">
    @Helpers.SearchPanel(text: "Nhập vào từ khóa tìm kiếm...", btnSearch: "btnSearch", txtSearch: "txtSearch")
</div>
@(Html.Osd().Grid<WeddingInvitation.Areas.Administrator.Models.StaticPageModel>(new List<WeddingInvitation.Areas.Administrator.Models.StaticPageModel>(), name: "StaticPage", controllerName: "StaticPage")
                    .Columns(columns =>
                    {
                        columns.Bound(x => x.StaticPageId).Title("ID").ClientTemplate("<a href=\"StaticPage/Edit/<#= StaticPageId #>\"><#= 10000 + StaticPageId #></a>")
                            .Width(100)
                            .Filterable(false);
                        columns.Bound(x => x.Description).Title("Mô tả")
                            .Sortable(false)
                            .Filterable(false);
                    }))