adidaphat.net.vn/trunk/WeddingInvitation/Areas/Administrator/Controllers/TransferController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using DotNetOpenAuth.OpenId.Extensions.AttributeExchange;
using Telerik.Web.Mvc;
using WeddingInvitation.Areas.Administrator.Models;
using WeddingInvitation.Core.Models.Storages;
using WeddingInvitation.Infrastructure;
using WeddingInvitation.Infrastructure.Mvc;
using WeddingInvitation.Services.Catalog;
using WeddingInvitation.Services.Infrastructure;
using WeddingInvitation.Services.Settings;
using WeddingInvitation.Services.Storages;
using WeddingInvitation.Services.Users;

namespace WeddingInvitation.Areas.Administrator.Controllers
{
    [Authorize]
    public class TransferController : ControllerBase<ITransferRepository, Transfer>
    {
        private readonly IMyOfficeRepository _myOfficeRepository;
        private readonly IProductRepository _productRepository;
        private readonly IProductInStorageRepository _productInStorageRepository;
        private readonly IStorageRepository _storageRepository;
        private readonly IImportDetailRepository _importDetailRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly IUserRepository _userRepository;
        private readonly ITransferItemRepository _transferItemRepository;
        private string TransferItemsSession = "TransferItemsSession";
        public List<TransferItemModel> TransferItems
        {
            get
            {
                if (Session[TransferItemsSession] == null)
                {
                    var transferItems = new List<TransferItemModel>();
                    Session[TransferItemsSession] = transferItems;
                    return transferItems;
                }
                return (List<TransferItemModel>)Session[TransferItemsSession];
            }
            set { Session[TransferItemsSession] = value; }
        }

        public TransferController(IUnitOfWork unitOfWork, ITransferRepository repository,
            IMyOfficeRepository myOfficeRepository, IProductRepository productRepository,
            IProductInStorageRepository productInStorageRepository, IStorageRepository storageRepository,
            IImportDetailRepository importDetailRepository, ICategoryRepository categoryRepository,
            IUserRepository userRepository, ITransferItemRepository transferItemRepository)
            : base(repository, unitOfWork)
        {
            _myOfficeRepository = myOfficeRepository;
            _productRepository = productRepository;
            _productInStorageRepository = productInStorageRepository;
            _storageRepository = storageRepository;
            _importDetailRepository = importDetailRepository;
            _categoryRepository = categoryRepository;
            _userRepository = userRepository;
            _transferItemRepository = transferItemRepository;
        }

        //
        // GET: /Administrator/MyOffice/

        public ActionResult Index()
        {
            var toStorages = _storageRepository.Search("").ToList();
            var storages = toStorages.Where(p => WorkContext.MyStorages.Contains(p.StorageId)).ToList();
            var model = new TransferModel
            {
                Storages = storages,
                ToStorages = toStorages
            };
            return View(model);
        }

        [GridAction]
        public ActionResult GridModel(ReportFilterModel filterModel)
        {
            //Default get all
            var fromDate = DateTime.Today;
            var isAllFromDate = true;
            var toDate = DateTime.Today;
            var isAllToDate = true;
            //Filter by date
            if (filterModel.FromDate.HasValue)
            {
                fromDate = filterModel.FromDate.Value.Date;
                isAllFromDate = false;
            }
            if (filterModel.ToDate.HasValue)
            {
                toDate = filterModel.ToDate.Value.Date.AddDays(1);
                isAllToDate = false;
            }
            var fromListStorages = new int[1];
            var isGetAllFromStorages = true;
            //Filter by deliver to
            if (filterModel.FromListStorages != null && filterModel.FromListStorages.Count() > 0)
            {
                fromListStorages = filterModel.FromListStorages;
                isGetAllFromStorages = false;
            }
            var toListStorages = new int[1];
            var isGetAllToStorages = true;
            //Filter by deliver to
            if (filterModel.ToListStorages != null && filterModel.ToListStorages.Count() > 0)
            {
                toListStorages = filterModel.ToListStorages;
                isGetAllToStorages = false;
            }

            var model = from x in Repository.Search(filterModel.search).Where(p => (fromListStorages.Contains(p.FromStorageId) || (isGetAllFromStorages && WorkContext.MyStorages.Contains(p.FromStorageId))) &&
                (toListStorages.Contains(p.ToStorageId) || (isGetAllToStorages && WorkContext.MyStorages.Contains(p.ToStorageId))) &&
                ((p.CreateDate >= fromDate || isAllFromDate) && (p.CreateDate <= toDate || isAllToDate)))
                        join m in _userRepository.GetAll() on x.ApproveFromManagerId equals m.UserId into m1
                        from m2 in m1.DefaultIfEmpty()
                        join s in _userRepository.GetAll() on x.ApproveFromStorageStaffId equals s.UserId into s1
                        from s2 in s1.DefaultIfEmpty()
                        join t in _userRepository.GetAll() on x.ApproveFromGeneralDeliveryManId equals t.UserId into t1
                        from t2 in s1.DefaultIfEmpty()
                        join h in _userRepository.GetAll() on x.ApproveFromReceiveStorageStaffId equals h.UserId into h1
                        from h2 in s1.DefaultIfEmpty()
                        select new TransferModel
                        {
                            TransferId = x.TransferId,
                            CreateDate = x.CreateDate,
                            Note = x.Note,
                            ApproveFromManagerName = (m2 == null ? String.Empty : m2.FirstName + " " + m2.LastName),
                            ApproveFromStorageStaffName = (s2 == null ? String.Empty : s2.FirstName + " " + s2.LastName),
                            ApproveFromGeneralDeliveryMan = (t2 == null ? String.Empty : t2.FirstName + " " + t2.LastName),
                            StorageStaffApproveReceive = (t2 == null ? String.Empty : t2.FirstName + " " + t2.LastName),
                        };

            var gridModel = new GridModel<TransferModel>
            {
                Data = model
            };
            return new JsonResult
            {
                Data = gridModel
            };
        }

        public ActionResult Create(int? mode, bool? blank)
        {
            if (!blank.HasValue || blank.Value)
            {
                TransferItems = new List<TransferItemModel>();
            }
            var toStorages = _storageRepository.Search("").ToList();
            var storages = toStorages.Where(p => WorkContext.MyStorages.Contains(p.StorageId)).ToList();
            var model = new TransferModel { CreateDate = DateTime.Now, Mode = mode, Storages = storages,ToStorages=toStorages};
            return View(model);
        }

        public virtual ActionResult Edit(int id)
        {
            var toStorages = _storageRepository.Search("").ToList();
            var storages = toStorages.Where(p => WorkContext.MyStorages.Contains(p.StorageId)).ToList();
            var entity = Repository.GetById(id);
            var model = new TransferModel
            {
                TransferId = entity.TransferId,
                Note = entity.Note,
                CreateDate = entity.CreateDate,
                Storages = storages,
                FromStorageId = entity.FromStorageId,
                ToStorageId = entity.ToStorageId,
                ToStorages =toStorages
            };
            return View("Edit", model);
        }

        [HttpPost, ValidateInput(false)]
        public virtual ActionResult Save(TransferModel model)
        {
            if (model.TransferId <= 0) //Create News
            {
                if (!ModelState.IsValid)
                {
                    var toStorages = _storageRepository.Search("").ToList();
                    var storages = toStorages.Where(p => WorkContext.MyStorages.Contains(p.StorageId)).ToList();
                    model.Storages = storages;
                    model.ToStorages = toStorages;
                    return View("Create", model);
                }
                if (!TransferItems.Any())
                {
                    SetErrorNotification(string.Format("Bạn chưa có sản phẩm nào."));
                    return RedirectToAction("Create", new { area = "Administrator" });
                }
                var entity = new Transfer
                {
                    IsDeleted = false,
                    CreateDate = model.CreateDate,
                    CreateUserId = WorkContext.CurrentUserId,
                    Note = model.Note,
                    ToStorageId = model.ToStorageId,
                    FromStorageId = model.FromStorageId,
                    TransferItems = new List<TransferItem>()
                };
                foreach (var transferItemModel in TransferItems)
                {
                    entity.TransferItems.Add(new TransferItem
                    {
                        Amount = transferItemModel.Amount,
                        ProductId = transferItemModel.ProductId,
                        Note = transferItemModel.Note,
                        IsDeleted = false
                    });
                }
                using (UnitOfWork)
                {
                    Repository.Insert(entity);
                }

            }

adidaphat.net.vn/trunk/WeddingInvitation/Areas/Administrator/Views/Transfer/ApproveFromGeneralDeliveryMan.cshtml
@{
    ViewBag.Title = "Xác nhận chuyển hàng cho kho ở tỉnh";
}
<script type="text/javascript">
    $(document).ready(function () {
        new SearchHelper($("#txtSearch"), $("#btnSearch"), $("#Transfer"));
    });
</script>
<div class="section-header">
    <div class="title">
        <img src="@Url.Content("~/Areas/Administrator/Content/Images/ico-catalog.png")" alt="" />
        Xác nhận chuyển hàng cho kho ở tỉnh
    </div>
</div>
@Helpers.SearchPanel(text: "Nhập vào từ khóa tìm kiếm...", btnSearch: "btnSearch", txtSearch: "txtSearch", showFromSearch: false)
@Html.Osd().HiddenPopupWindow("Cảnh Báo", Helpers.DeleteConfirmMessageBox("Bạn có thực sự muốn thực hiện thao tác này!", @Url.Action("ApproveFromGeneralDeliveryManDone", "Transfer", new { area = "administrator" })).ToHtmlString())
@(Html.Osd().Grid(new List<WeddingInvitation.Areas.Administrator.Models.TransferModel>(), name: "Transfer", action: "ApproveFromGeneralDeliveryManGridModel", controllerName: "Transfer", routeValues: null)
                    .Columns(columns =>
                    {
                        //columns.Bound(x => x.ImportTrackId).Title("ID").ClientTemplate("<label><#= 10000 + ImportTrackId #></label>")
                        //    .Width(100)
                        //    .Filterable(false);
                        columns.Bound(x => x.CreateDate).Title("Ngày Nhập").Format("{0:dd/MM/yyyy}")
                            .Width(250)
                            .Filterable(false);
                        columns.Bound(x => x.CreateUserName).Title("Nhân Viên Nhập")
                            .Filterable(false);
                        columns.Bound(p => p.TransferId)
                            .ClientTemplate("<a onclick='onMessageBoxDetail(<#= TransferId #>)'>Chi tiết</a>")
                            .HtmlAttributes(new { style = "text-align:center" })
                            .Title("")
                            .Width(100).Sortable(false)
                            .Filterable(false);
                        columns.Bound(p => p.TransferId)
                            .ClientTemplate("<a onclick='onMessageBoxActionDelete(<#= TransferId #>)'>Xác nhận</a>")
                            .HtmlAttributes(new { style = "text-align:center" })
                            .Title("")
                            .Width(100).Sortable(false)
                            .Filterable(false);
                        //columns.Bound(p => p.ImportTrackId)
                        //    .ClientTemplate("<a onclick='onMessageBoxActionDelete(<#= ImportTrackId #>, <#= StorageId #>)'><img src=\" ../Content/Images/delete_16_16.png\" /></a>")
                        //    .HtmlAttributes(new { style = "text-align:center" })
                        //    .Title(string.Empty)
                        //    .Width(100).Sortable(false)
                        //    .Filterable(false);
                    }))
@{ Html.Telerik().Window()
        .Name("ImportDetails")
        .Title("Chi tiết chuyển kho nội bộ")
        .Draggable(true)
        .Visible(false)
        .Modal(true)
        .Width(870)
        .Height(260)
        .Render();
}
<script type="text/javascript">
    function onMessageBoxDetail(id) {
        var window = $("#ImportDetails").data("tWindow");
        window.ajaxRequest($.validator.format("{0}/{1}", "@Url.Action("ListTransferItem", "Transfer")", id || ""));
        window.center().open();
    }
</script>

adidaphat.net.vn/trunk/WeddingInvitation/Areas/Administrator/Views/Transfer/Create.cshtml
@model WeddingInvitation.Areas.Administrator.Models.TransferModel

@{
    ViewBag.Title = "Chuyển kho nội bộ";
}
<table class="dashboard">
    <tr>
        <td class="maincol">
            @Html.Partial("_TransferViewDetail", ViewData)
        </td>
        <td class="rightcol">
            @Html.Action("CreateTransferItem", "Transfer", new { id = Model.TransferId })
        </td>
    </tr>
</table>
<script type="text/javascript">
    $(document).ready(function () {
        if ("@Model.Mode" == "1") {
            $(".rightcol").show();
        }
    });
    function openCreateForm() {
        $(".rightcol").show();
    }
    function hideCreateForm() {
        $(".rightcol").show();
    }

</script>

adidaphat.net.vn/trunk/WeddingInvitation/Areas/Administrator/Views/Transfer/Edit.cshtml
@model WeddingInvitation.Areas.Administrator.Models.TransferModel

@{
    ViewBag.Title = "Sửa chuyển kho nội bộ";
}
@Html.Partial("_TransferViewDetail", ViewData)

adidaphat.net.vn/trunk/WeddingInvitation/Areas/Administrator/Views/Transfer/ImportFromOtherStorage.cshtml
@model WeddingInvitation.Areas.Administrator.Models.TransferModel
@{
    ViewBag.Title = "Báo cáo nhập hàng từ kho khác";
}
<script type="text/javascript">
    $(document).ready(function () {
        new SearchHelper($("#txtSearch"), $("#btnSearch"), $("#Transfer"));
    });
</script>
<div class="section-header">
    <div class="title">
        <img src="@Url.Content("~/Areas/Administrator/Content/Images/ico-catalog.png")" alt="" />
        Báo cáo nhập hàng từ kho khác
    </div>
    <div class="options">
        <a onclick="Preview();" class="t-button">Xem</a>
    </div>
</div>
<table width="90%">
    <tr>
        <td>
            @Html.Label("Từ ngày")
        </td>
        <td>
            @Html.Label("Đến ngày")
        </td>
        <td>
            @Html.Label("Kho nhận")
        </td>
    </tr>
    <tr>
        <td>
            @(Html.Telerik().DatePicker()
                    .Name("FromDate")
                    .HtmlAttributes(new { id = "FromDate_wrapper" })
                    .ShowButton(true)
                    .Value(DateTime.Now)
            )
        </td>
        <td>
            @(Html.Telerik().DatePicker()
                    .Name("ToDate")
                    .HtmlAttributes(new { id = "ToDate_wrapper" })
                    .ShowButton(true)
                    .Value(DateTime.Now)
            )
        </td>
        <td>
            @Html.DropDownList("ToListStorages", new SelectList(Model.ToStorages, "StorageId", "StorageName"))
        </td>
    </tr>
</table>
<br />
@Helpers.SearchPanel(text: "Nhập vào từ khóa tìm kiếm...", btnSearch: "btnSearch", txtSearch: "txtSearch", showFromSearch: false)
@Html.Osd().HiddenPopupWindow("Cảnh Báo", Helpers.DeleteConfirmMessageBox("Bạn có thực sự muốn xóa không", @Url.Action("delete", "Transfer", new { area = "administrator"})).ToHtmlString())
@(Html.Osd().Grid(new List<WeddingInvitation.Areas.Administrator.Models.TransferModel>(), name: "Transfer", controllerName: "Transfer")
                    .Columns(columns =>
                    {
                        columns.Bound(x => x.TransferId).Title("ID").ClientTemplate("<label><#= 10000 + TransferId #></label>")
                            .Width(60)
                            .Filterable(false);
                        columns.Bound(x => x.CreateDate).Title("Ngày Nhập").Format("{0:dd/MM/yyyy}")
                            .Width(90)
                            .Filterable(false);
                        columns.Bound(x => x.FromStorageName).Title("Kho xuất")
                            .Width(120)
                            .Filterable(false);
                        columns.Bound(x => x.ToStorageName).Title("Kho nhập")
                            .Width(120)
                            .Filterable(false);
                        columns.Bound(x => x.CreateUserName).Title("Nhân Viên Nhập")
                            .Filterable(false);
                        columns.Bound(p => p.TransferId)
                            .ClientTemplate("<a onclick='onMessageBoxDetail(<#= TransferId #>)'>Chi tiết</a>")
                            .HtmlAttributes(new { style = "text-align:center" })
                            .Title("")
                            .Width(70).Sortable(false)
                            .Filterable(false);
                        columns.Bound(x => x.ApproveFromManagerName).Title("Xác nhận quản lý chung")
                            .Width(150)
                            .Filterable(false);
                        columns.Bound(x => x.ApproveFromStorageStaffName).Title("Xác nhận kho đi")
                            .Width(150)
                            .Filterable(false);
                        columns.Bound(x => x.ApproveFromGeneralDeliveryMan).Title("Xác nhận chuyển phát")
                            .Width(150)
                            .Filterable(false);
                        columns.Bound(x => x.StorageStaffApproveReceive).Title("Xác nhận kho nhận")
                            .Width(150)
                            .Filterable(false);
                        //columns.Bound(p => p.ImportTrackId)
                        //    .ClientTemplate("<a onclick='onMessageBoxActionDelete(<#= ImportTrackId #>, <#= StorageId #>)'><img src=\" ../Content/Images/delete_16_16.png\" /></a>")
                        //    .HtmlAttributes(new { style = "text-align:center" })
                        //    .Title(string.Empty)
                        //    .Width(100).Sortable(false)
                        //    .Filterable(false);
                    })
                    .ClientEvents(events => events.OnDataBinding("onDataBinding"))
                    .EnableCustomBinding(true))
@{ Html.Telerik().Window()
        .Name("ImportDetails")
        .Title("Chi tiết")
        .Draggable(true)
        .Visible(false)
        .Modal(true)
        .Width(870)
        .Height(260)
        .Render();
}
<script type="text/javascript">
    $(document).ready(function () {
        $("#ToListStorages").multiselect({
            header: true,
            selectedText: '#/# đã chọn',
            noneSelectedText: '- Chọn -',
            selectedList: 0,
            checkAllText: 'Chọn hết',
            uncheckAllText: 'Bỏ chọn'
        });
        $("#ToListStorages").multiselect("uncheckAll");
        jQuery.validator.methods["date"] = function (value, element) { return true; };
    });
    function onMessageBoxDetail(id) {
        var window = $("#ImportDetails").data("tWindow");
        window.ajaxRequest($.validator.format("{0}/{1}", "@Url.Action("ListTransferItem", "Transfer")", id || ""));
        window.center().open();
    }
    function Preview() {
        var fromDateTime = $('#FromDate').data('tDatePicker');
        var fromDate = $.telerik.formatString('{0:dd/MM/yyyy}', fromDateTime.value());
        var toDateTime = $('#ToDate').data('tDatePicker');
        var toDate = $.telerik.formatString('{0:dd/MM/yyyy}', toDateTime.value());
        var toListStorages = $("#ToListStorages").multiselect("getChecked").map(function () {
            return this.value;
        }).get();
        jQuery.ajaxSettings.traditional = true;
        $("#Transfer").data('tGrid')
                         .rebind({
                             FromDate: fromDate,
                             ToDate: toDate,
                             ToListStorages: toListStorages
                         });

    }
    function onDataBinding(e) {
        var fromDateTime = $('#FromDate').data('tDatePicker');
        var fromDate = $.telerik.formatString('{0:dd/MM/yyyy}', fromDateTime.value());
        var toDateTime = $('#ToDate').data('tDatePicker');
        var toDate = $.telerik.formatString('{0:dd/MM/yyyy}', toDateTime.value());
        var toListStorages = $("#ToListStorages").multiselect("getChecked").map(function () {
            return this.value;
        }).get();
        var searchModel = {
            FromDate: fromDate,
            ToDate: toDate,
            ToListStorages: toListStorages
        };
        e.data = searchModel;
    }
</script>

adidaphat.net.vn/trunk/WeddingInvitation/Areas/Administrator/Views/Transfer/Index.cshtml
@model WeddingInvitation.Areas.Administrator.Models.TransferModel
@{
    Layout = "~/Areas/Administrator/Views/Shared/_LayoutTwoColumns.cshtml";
    ViewBag.Title = "Báo cáo chuyển kho nội bộ";
}
<script type="text/javascript">
    $(document).ready(function () {
        new SearchHelper($("#txtSearch"), $("#btnSearch"), $("#Transfer"));
    });
</script>
<div class="section-header">
    <div class="title">
        <img src="@Url.Content("~/Areas/Administrator/Content/Images/ico-catalog.png")" alt="" />
        Báo cáo chuyển kho nội bộ
    </div>
    <div class="options">
        <a onclick="Preview();" class="t-button">Xem</a>
    </div>
</div>
<table width="90%">
    <tr>
        <td>
            @Html.Label("Từ ngày")
        </td>
        <td>
            @Html.Label("Đến ngày")
        </td>
        <td>
            @Html.Label("Kho chuyển")
        </td>
        <td>
            @Html.Label("Kho nhận")
        </td>
    </tr>
    <tr>
        <td>
            @(Html.Telerik().DatePicker()
                    .Name("FromDate")
                    .HtmlAttributes(new { id = "FromDate_wrapper" })
                    .ShowButton(true)
                    .Value(DateTime.Now)
            )
        </td>
        <td>
            @(Html.Telerik().DatePicker()
                    .Name("ToDate")
                    .HtmlAttributes(new { id = "ToDate_wrapper" })
                    .ShowButton(true)
                    .Value(DateTime.Now)
            )
        </td>
        <td>
            @Html.DropDownList("FromListStorages", new SelectList(Model.Storages, "StorageId", "StorageName"))
        </td>
        <td>
            @Html.DropDownList("ToListStorages", new SelectList(Model.ToStorages, "StorageId", "StorageName"))
        </td>
    </tr>
</table>
<br />
@Helpers.SearchPanel(text: "Nhập vào từ khóa tìm kiếm...", btnSearch: "btnSearch", txtSearch: "txtSearch", showFromSearch: false)
@Html.Osd().HiddenPopupWindow("Cảnh Báo", Helpers.DeleteConfirmMessageBox("Bạn có thực sự muốn xóa không", @Url.Action("delete", "Transfer", new { area = "administrator"})).ToHtmlString())
@(Html.Osd().Grid(new List<WeddingInvitation.Areas.Administrator.Models.TransferModel>(), name: "Transfer", controllerName: "Transfer")
                    .Columns(columns =>
                    {
                        columns.Bound(x => x.TransferId).Title("ID").ClientTemplate("<label><#= 10000 + TransferId #></label>")
                            .Width(70)
                            .Filterable(false);
                        columns.Bound(x => x.CreateDate).Title("Ngày Nhập").Format("{0:dd/MM/yyyy}")
                            .Width(100)
                            .Filterable(false);
                        columns.Bound(x => x.CreateUserName).Title("Nhân Viên Nhập")
                            .Filterable(false);
                        columns.Bound(p => p.TransferId)
                            .ClientTemplate("<a onclick='onMessageBoxDetail(<#= TransferId #>)'>Chi tiết</a>")
                            .HtmlAttributes(new { style = "text-align:center" })
                            .Title("")
                            .Width(70).Sortable(false)
                            .Filterable(false);
                        columns.Bound(x => x.ApproveFromManagerName).Title("Xác nhận quản lý chung")
                            .Width(150)
                            .Filterable(false);
                        columns.Bound(x => x.ApproveFromStorageStaffName).Title("Xác nhận kho đi")
                            .Width(150)
                            .Filterable(false);
                        //columns.Bound(x => x.ApproveFromGeneralDeliveryMan).Title("Xác nhận chuyển phát")
                        //    .Width(150)
                        //    .Filterable(false);
                        columns.Bound(x => x.StorageStaffApproveReceive).Title("Xác nhận kho nhận")
                            .Width(150)
                            .Filterable(false);
                        //columns.Bound(p => p.ImportTrackId)
                        //    .ClientTemplate("<a onclick='onMessageBoxActionDelete(<#= ImportTrackId #>, <#= StorageId #>)'><img src=\" ../Content/Images/delete_16_16.png\" /></a>")
                        //    .HtmlAttributes(new { style = "text-align:center" })
                        //    .Title(string.Empty)
                        //    .Width(100).Sortable(false)
                        //    .Filterable(false);
                    })
                    .ClientEvents(events => events.OnDataBinding("onDataBinding"))
                    .EnableCustomBinding(true))
@{ Html.Telerik().Window()
        .Name("ImportDetails")
        .Title("Chi tiết")
        .Draggable(true)
        .Visible(false)
        .Modal(true)
        .Width(870)
        .Height(260)
        .Render();
}
<script type="text/javascript">
    $(document).ready(function () {
        $("#FromListStorages").multiselect({
            header: true,
            selectedText: '#/# đã chọn',
            noneSelectedText: '- Chọn -',
            selectedList: 0,
            checkAllText: 'Chọn hết',
            uncheckAllText: 'Bỏ chọn'
        });
        $("#FromListStorages").multiselect("uncheckAll");
        $("#ToListStorages").multiselect({
            header: true,
            selectedText: '#/# đã chọn',
            noneSelectedText: '- Chọn -',
            selectedList: 0,
            checkAllText: 'Chọn hết',
            uncheckAllText: 'Bỏ chọn'
        });
        $("#ToListStorages").multiselect("uncheckAll");
        jQuery.validator.methods["date"] = function (value, element) { return true; };
    });
    function onMessageBoxDetail(id) {
        var window = $("#ImportDetails").data("tWindow");
        window.ajaxRequest($.validator.format("{0}/{1}", "@Url.Action("ListTransferItem", "Transfer")", id || ""));
        window.center().open();
    }
    function Preview() {
        var fromDateTime = $('#FromDate').data('tDatePicker');
        var fromDate = $.telerik.formatString('{0:dd/MM/yyyy}', fromDateTime.value());
        var toDateTime = $('#ToDate').data('tDatePicker');
        var toDate = $.telerik.formatString('{0:dd/MM/yyyy}', toDateTime.value());
        var fromListStorages = $("#FromListStorages").multiselect("getChecked").map(function () {
            return this.value;
        }).get();
        var toListStorages = $("#ToListStorages").multiselect("getChecked").map(function () {
            return this.value;
        }).get();
        jQuery.ajaxSettings.traditional = true;
        $("#Transfer").data('tGrid')
                         .rebind({
                             FromDate: fromDate,
                             ToDate: toDate,
                             FromListStorages: fromListStorages,
                             ToListStorages: toListStorages
                         });

    }
    function onDataBinding(e) {
        var fromDateTime = $('#FromDate').data('tDatePicker');
        var fromDate = $.telerik.formatString('{0:dd/MM/yyyy}', fromDateTime.value());
        var toDateTime = $('#ToDate').data('tDatePicker');
        var toDate = $.telerik.formatString('{0:dd/MM/yyyy}', toDateTime.value());
        var fromListStorages = $("#FromListStorages").multiselect("getChecked").map(function () {
            return this.value;
        }).get();
        var toListStorages = $("#ToListStorages").multiselect("getChecked").map(function () {
            return this.value;
        }).get();
        var searchModel = {
            FromDate: fromDate,
            ToDate: toDate,
            FromListStorages: fromListStorages,
            ToListStorages: toListStorages
        };
        e.data = searchModel;
    }
</script>

adidaphat.net.vn/trunk/WeddingInvitation/Areas/Administrator/Views/Transfer/_ListTransferItem.cshtml
@model WeddingInvitation.Areas.Administrator.Models.TransferModel
@{
    Layout = null;
}

<div class="section-header">
    <div class="title">
        <img src="@Url.Content("~/Areas/Administrator/Content/Images/ico-catalog.png")" alt="" />
        Sản phẩm
    </div>
</div>

@Html.Osd().HiddenPopupWindow("Cảnh Báo", Helpers.DeleteConfirmMessageBox("Bạn có thực sự muốn xóa không", @Url.Action("DeleteOrderDetail", "Order", new { area = "administrator" })).ToHtmlString())
@(Html.Telerik().Grid<WeddingInvitation.Areas.Administrator.Models.TransferItemModel>()
        .Name("Grid")
        .Columns(columns =>
        {
            columns.Bound(x => x.CategoryName).Title("Bộ")
                .Width(150)
                .Filterable(false);
            columns.Bound(x => x.ProductName).Title("Sản Phẩm")
                .Width(150)
                .Filterable(false);
            columns.Bound(x => x.AmountDisplay).Title("Số Lượng")
                .Width(100)
                .Filterable(false);
            columns.Bound(x => x.Note).Title("Ghi Chú")
                .Sortable(false)
                .Filterable(false);
        }).DataBinding(dataBinding => dataBinding.Ajax().Select("GridModelTransferItem", "Transfer", new { id = Model.TransferId }))
            .Groupable(grouping => grouping.Groups(groups =>
                        {
                            groups.Add(c => c.CategoryName);
                        }).Visible(false))
)